name: OARepo UI SPA CI Publish

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    needs: lint_and_test
    steps:
      - name: Build for production
        run: |
          quasar build
      - name: Set RELEASE_VERSION
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo $RELEASE_VERSION
      - name: Upload production dist artifact
        uses: actions/upload-artifact@v2
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        with:
          name: dist-spa-${{ RELEASE_VERSION }}
          path: |
            dist
            !dist/**/*.md
